apiVersion: v1
kind: ConfigMap
metadata:
    name: mysql-configmap
    labels:
        app: mysql
    namespace: databases
data:
    primary.cnf: |
        [mysqld]
        log-bin
    replica.cnf: |
        [mysqld]
        super-read-only
    