apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-data-disk
    namespace: databases
spec:
    accessModes: 
        -   ReadWriteOnce
    resources:
        requests:
            storage: 1Gi